server:
  port: 3030

spring:
  application:
    name: slackshot
  
  datasource:
    url: jdbc:h2:file:./slackshot_db
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  
  security:
    user:
      name: admin
      password: admin

logging:
  level:
    com.dlocal.slackshot: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

selenide:
  browser: chrome
  headless: false
  timeout: 30000
  polling-interval: 200
  reportsFolder: target/selenide-reports
  downloadsFolder: target/downloads
  browserSize: 1920x1200
  webdriverLogsEnabled: true
  screenshots: true
  savePageSource: false
  reopenBrowserOnFail: false
  clickViaJs: false
  remote: false
  browserBinary: "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
  pageLoadStrategy: normal
  proxyEnabled: false
  fileDownload: PROXY
  holdBrowserOpen: false
  fastSetValue: false
  runViaArachnid: false
  pageLoadTimeout: 60000
  scriptTimeout: 30000

screenshot:
  key: ${SCREENSHOT_KEY:default-screenshot-key}
  service:
    key: ${SCREENSHOT_SERVICE_KEY:default-service-key}

slack:
  service:
    key: ${SLACK_SERVICE_KEY:default-slack-key}

auth:
  key: ${AUTH_KEY:default-auth-key}

debug:
  port: 6060
  user: ${DEBUG_USER:user}
  pass: ${DEBUG_PASS:pass}

eventstore:
  host: ${EVENTSTORE_HOST:} 